
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
anovaOptions <- R6::R6Class(
    "anovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            nParamIters = 10000,
            dep = NULL,
            fullFactors = NULL,
            nullFactors = NULL,
            nullRow = -1,
            paramRow = -1,
            sort = NULL, ...) {

            super$initialize(
                package='BFX',
                name='anova',
                requiresData=TRUE,
                ...)
        
            private$..nParamIters <- jmvcore::OptionInteger$new(
                "nParamIters",
                nParamIters,
                min=1,
                default=10000)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..fullFactors <- jmvcore::OptionVariables$new(
                "fullFactors",
                fullFactors)
            private$..nullFactors <- jmvcore::OptionVariables$new(
                "nullFactors",
                nullFactors)
            private$..nullRow <- jmvcore::OptionInteger$new(
                "nullRow",
                nullRow,
                default=-1,
                hidden=TRUE)
            private$..paramRow <- jmvcore::OptionInteger$new(
                "paramRow",
                paramRow,
                default=-1,
                hidden=TRUE)
            private$..sort <- jmvcore::OptionSort$new(
                "sort",
                sort,
                default=NULL,
                hidden=TRUE,
                passive=TRUE)
        
            self$.addOption(private$..nParamIters)
            self$.addOption(private$..dep)
            self$.addOption(private$..fullFactors)
            self$.addOption(private$..nullFactors)
            self$.addOption(private$..nullRow)
            self$.addOption(private$..paramRow)
            self$.addOption(private$..sort)
        }),
    active = list(
        nParamIters = function() private$..nParamIters$value,
        dep = function() private$..dep$value,
        fullFactors = function() private$..fullFactors$value,
        nullFactors = function() private$..nullFactors$value,
        nullRow = function() private$..nullRow$value,
        paramRow = function() private$..paramRow$value,
        sort = function() private$..sort$value),
    private = list(
        ..nParamIters = NA,
        ..dep = NA,
        ..fullFactors = NA,
        ..nullFactors = NA,
        ..nullRow = NA,
        ..paramRow = NA,
        ..sort = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
anovaResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        anova = function() private$..anova,
        state = function() private$..state,
        param = function() private$..param),
    private = list(
        ..anova = NA,
        ..state = NA,
        ..param = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Bayesian ANOVA")
            private$..anova <- jmvcore::Table$new(
                options=options,
                name="anova",
                title="Bayesian ANOVA",
                rowSelect="(nullRow)",
                sortSelect="(sort)",
                columns=list(
                    list(`name`="model", `title`="", `type`="text", `sortable`=TRUE, `content`="($key)"),
                    list(`name`="bf", `title`="BF", `type`="number", `sortable`=TRUE),
                    list(`name`="err", `title`="Error", `type`="number", `format`="pc")))
            private$..state <- jmvcore::State$new(
                options=options,
                name="state",
                clearWith=list(
                    "dep",
                    "fullFactors",
                    "nullFactors"))
            private$..param <- jmvcore::Table$new(
                options=options,
                name="param",
                title="Parameter estimates",
                rowSelect="(paramRow)",
                columns=list(
                    list(`name`="param", `title`="Parameter", `type`="text"),
                    list(`name`="mean", `title`="Mean", `type`="number")))
            self$add(private$..anova)
            self$add(private$..state)
            self$add(private$..param)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
anovaBase <- R6::R6Class(
    "anovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BFX',
                name = 'anova',
                version = c(1,0,0),
                options = options,
                results = anovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian ANOVA
#'
#' 
#' @param data .
#' @param nParamIters .
#' @param dep .
#' @param fullFactors .
#' @param nullFactors .
#' @param nullRow .
#' @param paramRow .
#' @param sort .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$anova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$state} \tab \tab \tab \tab \tab a state \cr
#'   \code{results$param} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anova$asDF}
#'
#' \code{as.data.frame(results$anova)}
#'
#' @export
anova <- function(
    data,
    nParamIters = 10000,
    dep,
    fullFactors,
    nullFactors,
    nullRow = -1,
    paramRow = -1,
    sort = NULL) {

    options <- anovaOptions$new(
        nParamIters = nParamIters,
        dep = dep,
        fullFactors = fullFactors,
        nullFactors = nullFactors,
        nullRow = nullRow,
        paramRow = paramRow,
        sort = sort)

    results <- anovaResults$new(
        options = options)

    analysis <- anovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
