
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
regressionOptions <- R6::R6Class(
    "regressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            nParamIters = 10000,
            showAIC = TRUE,
            showBIC = TRUE,
            dep = NULL,
            predictors = NULL,
            nullRow = -1,
            paramRow = -1,
            selSort = NULL, ...) {

            super$initialize(
                package='BFX',
                name='regression',
                requiresData=TRUE,
                ...)
        
            private$..nParamIters <- jmvcore::OptionInteger$new(
                "nParamIters",
                nParamIters,
                min=1,
                default=10000)
            private$..showAIC <- jmvcore::OptionBool$new(
                "showAIC",
                showAIC,
                default=TRUE)
            private$..showBIC <- jmvcore::OptionBool$new(
                "showBIC",
                showBIC,
                default=TRUE)
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..predictors <- jmvcore::OptionVariables$new(
                "predictors",
                predictors)
            private$..nullRow <- jmvcore::OptionInteger$new(
                "nullRow",
                nullRow,
                default=-1,
                hidden=TRUE)
            private$..paramRow <- jmvcore::OptionInteger$new(
                "paramRow",
                paramRow,
                default=-1,
                hidden=TRUE)
            private$..selSort <- jmvcore::OptionSort$new(
                "selSort",
                selSort,
                default=NULL,
                hidden=TRUE,
                passive=TRUE)
        
            self$.addOption(private$..nParamIters)
            self$.addOption(private$..showAIC)
            self$.addOption(private$..showBIC)
            self$.addOption(private$..dep)
            self$.addOption(private$..predictors)
            self$.addOption(private$..nullRow)
            self$.addOption(private$..paramRow)
            self$.addOption(private$..selSort)
        }),
    active = list(
        nParamIters = function() private$..nParamIters$value,
        showAIC = function() private$..showAIC$value,
        showBIC = function() private$..showBIC$value,
        dep = function() private$..dep$value,
        predictors = function() private$..predictors$value,
        nullRow = function() private$..nullRow$value,
        paramRow = function() private$..paramRow$value,
        selSort = function() private$..selSort$value),
    private = list(
        ..nParamIters = NA,
        ..showAIC = NA,
        ..showBIC = NA,
        ..dep = NA,
        ..predictors = NA,
        ..nullRow = NA,
        ..paramRow = NA,
        ..selSort = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
regressionResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        models = function() private$..models,
        state = function() private$..state,
        estimateState = function() private$..estimateState,
        param = function() private$..param,
        postPlot = function() private$..postPlot,
        htmlTest = function() private$..htmlTest),
    private = list(
        ..models = NA,
        ..state = NA,
        ..estimateState = NA,
        ..param = NA,
        ..postPlot = NA,
        ..htmlTest = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Bayesian linear regression")
            private$..models <- jmvcore::Table$new(
                options=options,
                name="models",
                title="Models",
                rowSelect="(nullRow)",
                sortSelect="(selSort)",
                columns=list(
                    list(`name`="model", `title`="", `type`="text", `content`="($key)"),
                    list(`name`="p", `title`="# predictors", `type`="integer", `sortable`=TRUE),
                    list(`name`="R2", `title`="R\u00B2", `type`="number", `sortable`=TRUE),
                    list(`name`="bf", `title`="BF", `type`="number", `sortable`=TRUE),
                    list(`name`="aic", `title`="\u0394AIC", `type`="number", `sortable`=TRUE, `visible`="(showAIC)"),
                    list(`name`="bic", `title`="\u0394BIC", `type`="number", `sortable`=TRUE, `visible`="(showBIC)")))
            private$..state <- jmvcore::State$new(
                options=options,
                name="state",
                clearWith=list(
                    "dep",
                    "predictors"))
            private$..estimateState <- jmvcore::State$new(
                options=options,
                name="estimateState",
                clearWith=list(
                    "dep",
                    "predictors"))
            private$..param <- jmvcore::Table$new(
                options=options,
                name="param",
                title="Parameter estimates",
                rowSelect="(paramRow)",
                columns=list(
                    list(`name`="param", `title`="Posterior parameter estimates", `type`="text"),
                    list(`name`="mean", `title`="Mean", `type`="number"),
                    list(`name`="sd", `title`="SD", `type`="number")))
            private$..postPlot <- jmvcore::Image$new(
                options=options,
                name="postPlot",
                title="Posterior distribution",
                width=400,
                height=300,
                renderFun=".postPlot")
            private$..htmlTest <- jmvcore::Html$new(
                options=options,
                name="htmlTest",
                title="HTML test")
            self$add(private$..models)
            self$add(private$..state)
            self$add(private$..estimateState)
            self$add(private$..param)
            self$add(private$..postPlot)
            self$add(private$..htmlTest)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
regressionBase <- R6::R6Class(
    "regressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'BFX',
                name = 'regression',
                version = c(1,0,0),
                options = options,
                results = regressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian linear regression
#'
#' 
#' @param data .
#' @param nParamIters .
#' @param showAIC .
#' @param showBIC .
#' @param dep .
#' @param predictors .
#' @param nullRow .
#' @param paramRow .
#' @param selSort .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$models} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$state} \tab \tab \tab \tab \tab a state \cr
#'   \code{results$estimateState} \tab \tab \tab \tab \tab a state \cr
#'   \code{results$param} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$postPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$htmlTest} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$models$asDF}
#'
#' \code{as.data.frame(results$models)}
#'
#' @export
regression <- function(
    data,
    nParamIters = 10000,
    showAIC = TRUE,
    showBIC = TRUE,
    dep,
    predictors,
    nullRow = -1,
    paramRow = -1,
    selSort = NULL) {

    options <- regressionOptions$new(
        nParamIters = nParamIters,
        showAIC = showAIC,
        showBIC = showBIC,
        dep = dep,
        predictors = predictors,
        nullRow = nullRow,
        paramRow = paramRow,
        selSort = selSort)

    results <- regressionResults$new(
        options = options)

    analysis <- regressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
